image: archlinux
sources:
  - https://git.sr.ht/~pehwo/doli_csv
packages:
  - python34
  - python35
  - python36
  - python
tasks:
  - pip: |
      sudo pip3 install --upgrade pip
      sudo pip3 install poetry
  - setup: |
      cd doli_csv
      poetry install
  - test: |
      cd doli_csv
      poetry run tox
