image: archlinux
sources:
  - https://git.sr.ht/~pehwo/doli_csv
packages:
  - python
  - python-pip
tasks:
  - pip: |
      sudo pip install poetry
  - test_py37: |
      cd doli_csv
      poetry run tox
