image: archlinux
sources:
  - https://git.sr.ht/~pehwo/doli_csv
packages:
  - openssl
  - python
  - python-pip
  - pyenv
tasks:
  - pyenv: |
       pyenv install 3.5.5
       pyenv install 3.6.6
       pyenv install 3.7.0
  - pip: |
      pip install --user poetry
  - setup: |
      cd doli_csv
      pyenv local 3.5.5 3.6.6 3.7.0
      poetry install
  - test: |
      cd doli_csv
      poetry run tox
