image: archlinux
sources:
  - https://git.sr.ht/~pehwo/doli_csv
packages:
  - openssl
  - python
  - python-pip
  - pyenv
tasks:
  - pip: |
      sudo pip install poetry
  - setup: |
      cd doli_csv
      poetry install
  - test_py37: |
      cd doli_csv
      poetry run pytest
  - pyenv: |
       pyenv install 3.5.5
       pyenv install 3.6.6
  - test_tox: |
      cd doli_csv
      pyenv local 3.5.5 3.6.6
      poetry run tox
